version: '3.9'

services:

  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    container_name: ${PROJECT_NAME}-webserver
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PROXY_HTTP_PORT}:80
    networks:
      - backend


  php-fpm:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    container_name: ${PROJECT_NAME}-php-fpm
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - backend
    links:
      - postgres
      - redis

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ./redis-data:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend


  postgres:
    image: postgres:13.2
    container_name: ${PROJECT_NAME}-postgres
    working_dir: /application
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ../:/application
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - backend


#  mysql:
#    image: mysql:8.0.23
#    container_name: ${PROJECT_NAME}-mysql
#    working_dir: /application
#    restart: unless-stopped
#    volumes:
#      - ./mysql-data:/var/lib/mysql
#      - ../:/application
#    environment:
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    ports:
#      - ${MYSQL_PORT}:3306

  cron:
    build:
      context: ../
      dockerfile: docker/php_cron/Dockerfile
    container_name: ${PROJECT_NAME}-cron
    working_dir: /application
    restart: unless-stopped
    volumes:
      - ../:/application
    networks:
      - backend
    links:
      - postgres
      - redis


  queue-worker:
    build:
      context: ../
      dockerfile: docker/php-fpm/Dockerfile
    container_name: ${PROJECT_NAME}-queue-worker
    restart: unless-stopped
    working_dir: /application
    volumes:
      - ../:/application
      - ../docker/php_cli/php-ini-overrides.ini:/etc/php/7.4/cli/conf.d/99-overrides.ini
    command: [ "php", "artisan", "queue:listen", "--delay=0", "--tries=3" ]
    networks:
      - backend
    links:
      - postgres
      - redis


networks:
  backend:
    name: ${PROJECT_NAME}_network
    driver: bridge


volumes:
  postgres:
  redis:
